### ISSUE TITLE
Some more variables requested by WP6 members

### ISSUE THREAD

**Issue by ozanmert** [impetus4change/T32-CPRCM#3]
Hi @pia-freisen @jesusff ,

Lu Li (NORCE) from WP6 requested the following variables:

Surface runoff: mrros (in WRF output named: SRFOFF)
Snow water equivalent: snw
Total soil moisture content: mrso
Total runoff: mrro
Underground runoff:  (in WRF output named: UDROFF)

Thanks!

**Comment by jesusff** [comment]
OK, these are in the CORDEX-CMIP6 as Tier1 variables. Which frequency would be required?
Underground runoff is usually not stored, as `subsurface_runoff_flux = runoff_flux - surface_runoff_flux`

**Comment by ozanmert** [comment]
Thanks @jesusff . So, these are needed in **1 hr** frequency:

Surface runoff: mrros 
Snow water equivalent: snw
Total soil moisture content: mrso
Total runoff: mrro
